# .github/workflows/main_entityhub.yml

name: Build and deploy Node.js app to Azure Web App - EntityHub

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js version
        run: |
          sudo apt-get install -y nodejs
          sudo apt-get install -y npm
          sudo npm install -g n
          sudo n 20.11.0
          sudo ln -sf /usr/local/n/versions/node/20.11.0/bin/node /usr/bin/node
          sudo ln -sf /usr/local/n/versions/node/20.11.0/bin/npm /usr/bin/npm

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'EntityHub'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_66D79450107D4AF49EBAC59F32B0B252 }}
          package: .





